In [1]:
import numpy as np

In [2]:
array_1=np.array([1,2,3])  #it will by default look like list.
print(array_1)

[1 2 3]


In [3]:
array_2=np.array((38,40,50))
print(array_2)

[38 40 50]


In [5]:
array_3=np.array([[1,2,3],[4,5,6]])
print(array_3)

[[1 2 3]
 [4 5 6]]


In [6]:
array_4=np.array([[1,2,3],[4,5,6],[5,6,7]])
print(array_4)

[[1 2 3]
 [4 5 6]
 [5 6 7]]


In [7]:
# BASIC METHODS THAT CAN BE USED IN NUMPY.
np.array([1,2,3,4],dtype="complex")

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [8]:
np.array([1,2,3,4],dtype="float")

array([1., 2., 3., 4.])

In [9]:
print(array_1+array_2)

[39 42 53]


In [11]:
list_1=[1,2,3]
list_2=[30,40,50]
print(list_1+list_2)  #here it do concatination

[1, 2, 3, 30, 40, 50]


In [12]:
list_ans=[]
for i, j in zip(list_1,list_2):
    list_ans.append(i+j)
print(list_ans)

[31, 42, 53]


In [13]:
#METHOD: how to check dimension of array.
array_1.ndim

1

In [14]:
array_3.ndim

2

In [15]:
#METHOD: how to check shape of array(matrix)
array_1.shape

(3,)

In [17]:
array_4.shape

(3, 3)

In [18]:
#METHOD: how can we check the size of array.
array_4.size

9

In [23]:
a1=np.arange(10)    #it only creates 1d array.and helps to create array same as range function.
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
a2=np.arange(12,dtype="float")
print(a2)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [27]:
a2=np.arange(12,dtype="float").reshape(4,3) #dtype changes data type.
print(a2)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [26]:
a1=np.arange(10).reshape(5,2)  #here 1d is converted to 2d.
print(a1)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [30]:
a2=a2.astype(np.int64)    #changing the data tupe of the array.
print(a2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [31]:
# basic operations on array.
a2*4

array([[ 0,  4,  8],
       [12, 16, 20],
       [24, 28, 32],
       [36, 40, 44]])

In [33]:
#running for loop on array. it also picks rows.
for i in a2:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [34]:
#when you want to reach out the elements or values of array or matrix.
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [36]:
print(a2>5)

[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]
