In [1]:
import pandas as pd

In [2]:
#from sklearn.datasets import load_boston
df=pd.read_csv("C:/Users/Asus/Downloads/load_boston_final_lyst1729240745225.csv")

In [3]:
df

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,target_col
0,0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0


In [4]:
#training the data.
#Step 1-splitting or x and y.

x=df.iloc[:,1:14]
y=df.iloc[:,-1]

In [5]:
x

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48


In [6]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: target_col, Length: 506, dtype: float64

In [7]:
# Train test

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=78)

In [8]:
#scaling the data so that different scales of the dataset enteries becomes equal.

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [9]:
from sklearn.linear_model import LinearRegression
lm=LinearRegression()
lm.fit(x_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [10]:
y_pred=lm.predict(x_test)

In [11]:
y_pred

array([13.41764528, 22.26142597,  5.67176254, 24.42660604, 13.90585069,
       27.94043383, 18.49573112, 28.55487366, 24.96356791, 33.16899933,
       22.22293947, 22.99323649, 25.42586054, 25.84633593, 41.87656627,
       23.24579135, 13.74785832, 30.06760276, 30.69945682, 15.45301492,
       31.11562818, 11.3210182 , 28.31558925, 19.43427147, 15.63458748,
        3.98714511,  3.40810155, 21.59847624, 23.88921469, 32.68119111,
       36.50619839, 25.34218081, 14.36055887, 23.32279658, 32.51802733,
       28.42131701, 27.85042304, 16.57061952, 32.85275869, 16.41328857,
       28.40002524, 19.92319568, 21.80808685, 24.06773175, 40.01174346,
       17.74903794, 30.24481875, 25.56817434, 13.57999959, 33.7501883 ,
       25.00993075, 25.25088637, 24.13688889, 19.18982473, 27.03104009,
       17.88739594, 23.20172228, 21.62107495, 24.04709787, 24.26324324,
       18.25920479, 12.60851248, 11.5250957 , 27.72391717, 21.04841849,
       20.70840066, 23.25160755, 26.05127631, 25.99603874, 23.12

In [12]:
y_test

456    12.7
45     19.3
387     7.4
242    22.2
496    19.7
       ... 
127    16.2
243    23.7
110    21.7
434    11.7
303    33.1
Name: target_col, Length: 152, dtype: float64

In [13]:
# finding the score of the model.

lm.score(x_train,y_train)

0.7213692113683383

In [14]:
# performing cross validation

from sklearn.model_selection import cross_val_score

In [20]:
c_v=cross_val_score(lm,x_train,y_train,scoring="neg_mean_squared_error",cv=10)
c_v_1=cross_val_score(lm,x_train,y_train,scoring="neg_mean_absolute_error",cv=10)

In [16]:
c_v

array([-15.24511841, -34.58404591, -25.25631946, -19.94338566,
       -10.43994958, -41.33771978, -31.77370926, -16.11873464,
       -25.0613627 , -21.65297995])

In [19]:
# mean square error before cross validation. 
#differen the actual value and pred value then its square andclaculating the average value.

from sklearn.metrics import mean_squared_error, mean_absolute_error
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

#this is the error before cross validation. its is high.

3.6425146787401133
24.59235469266049


In [18]:
# finding the mean of c_v
# thsi is the error after cross validation and it got reduced.

c_v.mean()

np.float64(-24.141332534894214)

In [21]:
c_v_1

array([-2.57327642, -4.1428935 , -3.4385946 , -3.3752797 , -2.34245148,
       -4.66376401, -3.43739052, -3.13117554, -3.56185364, -3.26463714])

In [22]:
c_v_1.mean()

np.float64(-3.3931316535251552)

In [23]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [24]:
ridge_1=Ridge()

In [27]:
# tuning the  hyper parameters for the values od lamda/alpha

parameters={"alpha":[1,2,3,4,5,6,7,10,30,40,50,70,45]}

ridge_cv=GridSearchCV(ridge_1,parameters,scoring="neg_mean_squared_error",cv=5)

In [29]:
# training the ridge model

ridge_cv.fit(x_train,y_train)

,estimator,Ridge()
,param_grid,"{'alpha': [1, 2, ...]}"
,scoring,'neg_mean_squared_error'
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,alpha,2


In [30]:
# finding the optimal value of the alpha/lamda

ridge_cv.best_params_

{'alpha': 2}

In [31]:
# predicting for ridge.

ridge_predict=ridge_cv.predict(x_test)

In [32]:
# checking the R2 score

from sklearn.metrics import r2_score
r2_score(ridge_predict,y_test)

0.5938703563048247

In [33]:
# r2 score for normal lieanr regression model 
# since the data set was perfect anda was not overfitted so we dont have to perform ridge regualrisation.

r2_score(y_test,y_pred)

0.7504710875357788

In [34]:
from sklearn.linear_model import Lasso

In [35]:
lasso_1=Lasso()

In [36]:
# performing hyper parameter tuning for lasso regularisation.
# tuning the  hyper parameters for the values od lamda/alpha

parameters={"alpha":[1,2,3,4,5,6,7,10,30,40,50,70,45]}

lasso_cv=GridSearchCV(lasso_1,parameters,scoring="neg_mean_squared_error",cv=5)
# training the data.
lasso_cv.fit(x_train,y_train)


,estimator,Lasso()
,param_grid,"{'alpha': [1, 2, ...]}"
,scoring,'neg_mean_squared_error'
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,alpha,1


In [37]:
# doing prediction for lasso 

lasso_pred=lasso_cv.predict(x_test)

In [39]:
# calculating the r2 score for lasso

r2_score(y_test,lasso_pred)

0.6449485463332955