In [1]:
import numpy as np

In [2]:
var_1=np.array([1,2,3,4])
print(var_1)

[1 2 3 4]


In [3]:
var_2=np.array([[1,2,3],[4,5,6]])
print(var_2)

[[1 2 3]
 [4 5 6]]


In [4]:
#array of zero:-
var_3=np.zeros((3,3),dtype=int)
print(var_3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
#array of ones:-
var_4=np.ones((4,4),dtype=int)
print(var_4)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [6]:
#array of random elements:-
#here we can not change the data type as it gives random value.
#everytime we run it it gives differeent values.
var_5=np.random.rand(4,4)
print(var_5)

[[0.98994112 0.88165954 0.06399708 0.36857663]
 [0.08810494 0.03467062 0.91665461 0.98874761]
 [0.80815988 0.04121469 0.57965955 0.68469866]
 [0.44312172 0.09062669 0.15821749 0.43070378]]


In [7]:
#fixing the values of random arrays.
#you can give any number it dosent have any association with the arrays .
np.random.seed(4)
var_5=np.random.rand(4,4)
print(var_5)

[[0.96702984 0.54723225 0.97268436 0.71481599]
 [0.69772882 0.2160895  0.97627445 0.00623026]
 [0.25298236 0.43479153 0.77938292 0.19768507]
 [0.86299324 0.98340068 0.16384224 0.59733394]]


In [8]:
# here n in randn means negative so it will also show negative values.
#the values can be fixed by the same method as above.
np.random.seed(1)
var_6=np.random.randn(4,4)
print(var_6)

[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862]
 [ 0.86540763 -2.3015387   1.74481176 -0.7612069 ]
 [ 0.3190391  -0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944 -1.09989127]]


In [9]:
# here randint is used to get only integer values . 
#and we have to mention the range
#same method will be used to fix the numbers.
np.random.seed(1)
var_7=np.random.randint(low=50,high=100,size=(4,4))
print(var_7)

[[87 93 62 58]
 [59 61 55 65]
 [50 66 51 62]
 [57 95 56 75]]


In [10]:
help(np.random.randint)

Help on method randint in module numpy.random:

randint(low, high=None, size=None, dtype=<class 'int'>) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, o

__SLICING AND INDEXING:-
    ->INEXING:- (row ,coulmn)
        INEXING ACROSS THE ROWS 
        INEXING ACROSS THE COLUMNS
    ->SLICING:- x(for row starting index position: ending position,column same as row)
        WE WILL PERFORM SLICING IN SAME MANNER LIKE WE USE TO O IN LIST AND TUPE.
        HERE WE WILL EXTRACT A SUB MATRIX FROM A COMPLETE MATRIX.

In [11]:
#INEXING
print(var_7)

[[87 93 62 58]
 [59 61 55 65]
 [50 66 51 62]
 [57 95 56 75]]


In [12]:
print(var_7[1,1])

61


In [13]:
#SLICING:
print(var_7[0:2,0:2])

[[87 93]
 [59 61]]


In [14]:
print(var_7[2:3,2:])

[[51 62]]


In [16]:
#CREATION OF IDENTITY MATRIX:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [20]:
#RESHAPE:
a=np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
#CONVERT 2D INTO 1D:
a=a.ravel()
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [24]:
#TRANSPOSE:
b=np.arange(1,13).reshape(4,3)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
b.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [32]:
c=np.arange(12).reshape(3,4)
d=np.arange(12,24).reshape(3,4)

In [30]:
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [31]:
print(d)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [37]:
#STACKING: 
#--here v refers to vertival stacking.
e=np.vstack((c,d))
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [38]:
#--here h refers to horizontal stacking.
f=np.hstack((c,d))
print(f)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [42]:
#SPLITTING:-
#here h is horizontal splitting
np.hsplit(e,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [43]:
#here v is vertically splitting.
np.vsplit(e,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]